services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "8000:8080"
    volumes:
      - ./web:/app/public

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./api:/app
      - /app/node_modules

  database:
    build: 
        context: ./database
        dockerfile: Dockerfile
    ports:
      - "8002:5432"
    volumes:
      - database_data:/var/lib/postgresql/data
      - ./database/database.sql:/docker-entrypoint-initdb.d/database.sql

volumes:
  database_data: